//
//  main.swift
//  FGF
//
//  Created by Aurélien Waxin on 19/04/2021.
//

import Foundation


let game = Game()
game.startGame()
game.createTeams()
game.startBattle()
//let attacker = Warrior(name: "Attacker")
//let guerisseur = Priest(name: "guerisseur")
//let ennemy = Warrior(name: "ennemy")
//let allié = Lumberjack(name: "Allié")
//print("FIGHT")
//print(ennemy.life)
//print(allié.life)
//print("Attaque sur allié ")
//print("Guerison pour ennemy")
//attacker.actionOn(otherCharacter: allié)
//guerisseur.actionOn(otherCharacter: ennemy)
//print(ennemy.life)
//print(allié.life)
//print("Attention contre attaque")
//attacker.actionOn(otherCharacter: allié)
//attacker.actionOn(otherCharacter: ennemy)
//print(ennemy.life)
//print(allié.life)
//print("GUERISON x2")
//guerisseur.actionOn(otherCharacter: ennemy)
//guerisseur.actionOn(otherCharacter: ennemy)
//guerisseur.actionOn(otherCharacter: allié)
//guerisseur.actionOn(otherCharacter: allié)
//print(ennemy.life)
//print(allié.life)
//guerisseur.actionOn(otherCharacter: ennemy)
//print(ennemy.life)
//guerisseur.actionOn(otherCharacter: ennemy)
//print(ennemy.life)
//print("Ennemy trop soigné (!)")
//guerisseur.actionOn(otherCharacter: allié)
//guerisseur.actionOn(otherCharacter: allié)
//guerisseur.actionOn(otherCharacter: allié)
//print(allié.life)
//guerisseur.actionOn(otherCharacter: allié)
//guerisseur.actionOn(otherCharacter: allié)
//print("ATTAQUE FUNC")
//print(ennemy.life)
//guerisseur.attack(target: ennemy)
//print(ennemy.life)
//allié.attack(target: ennemy)
//print(ennemy.life)
//allié.attack(target: ennemy)
//print(ennemy.life)
//allié.attack(target: ennemy)
//print(ennemy.life)
//allié.attack(target: ennemy)
